routes/web.php
<?php
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SachController;
use App\Http\Controllers\DanhmucController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserpageController;
use App\Http\Controllers\QuanlyMuonsachController;
use App\Http\Controllers\ThanhvienController;
use App\Http\Controllers\MuonsachController;
use App\Models\DanhmucSach;
use App\Http\Controllers\DdcController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     $danhmuc = DanhmucSach::orderBy('id_Danhmuc','DESC')->get();
//     return view('homepage.userpage')->with(compact('danhmuc'));
// });

Route::get('/',[UserpageController::class, 'index']);
Route::get('ddc/{slugDDC}',[UserpageController::class, 'ddc']);
Route::get('/danh-muc/{slugdanhmuc}',[UserpageController::class, 'danhmuc']);
Route::get('/chi-tiet/{slugsach}',[UserpageController::class, 'chitiet'])->middleware('auth');
Route::get('/tim-kiem',[UserpageController::class, 'timkiem']);
Route::post('/muon-sach-1',[MuonsachController::class, 'store']);
Route::get('/muon-sach',[MuonsachController::class, 'index'])->middleware('auth');
Route::get('/the-thanh-vien',[UserpageController::class, 'thethanhvien'])->middleware('auth');







Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home')->middleware('checklogin');
Route::resource('/danhmucsach',DanhmucController::class);
Route::resource('/ddc',DdcController::class);
Route::resource('/sach',SachController::class);
Route::resource('/dashboard',DashboardController::class);
Route::get('/quanlymuonsach',[QuanlyMuonsachController::class, 'index'])->middleware('auth');
Route::get('/quanlymuonsach/require',[QuanlyMuonsachController::class, 'require'])->middleware('auth');
Route::post('/quanlymuonsach/dongy',[QuanlyMuonsachController::class, 'dongy']);
Route::post('/quanlymuonsach/tuchoi',[QuanlyMuonsachController::class, 'tuchoi']);
Route::post('/quanlymuonsach/datra',[QuanlyMuonsachController::class, 'datra']);
Route::resource('/thanhvien',ThanhvienController::class);





    
// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

<div class="container" style="margin-left:0;">
    <div class="row" style="width:100vw;">
        <div class="sidebar">
            <div class="navigation">
                <ul>
                    <li>
                        <a href="{{url('/home')}}">
                            <span class="icon"><img src="{{asset('images/favicon.ico')}}"</i>
                            </span>
                            <span class="title">Thư viện Mini</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{route('dashboard.index')}}">
                            <span class="icon"><i class="fa fa-home" aria-hidden="true"></i>
                            </span>
                            <span class="title">Dashboard</span>
                        </a>
                    </li>
                    <li>
                        <a href="#" onclick="showDDC()">
                            <span class="icon"><i class="fa fa-list-alt" aria-hidden="true"></i>
                            </span>
                            <span class="title">DDC</span>
                            <span class="icon"><i class="fa fa-caret-down" aria-hidden="true"></i>
                            </span>
                        </a>
                        <ul class="DDC-show">
                            <li><a href="{{route('ddc.create')}}"><span class="title">Add DDC</span></a></li>
                            <li><a href="{{route('ddc.index')}}"><span class="title">Show DDC</span></a></li>
                        </ul>

                    </li>
                    <li>
                        <a href="#" onclick="showcategory()">
                            <span class="icon"><i class="fa fa-list" aria-hidden="true"></i>
                            </span>
                            <span class="title">Category</span>
                            <span class="icon"><i class="fa fa-caret-down" aria-hidden="true"></i>
                            </span>
                        </a>
                        <ul class="category-show">
                            <li><a href="{{route('danhmucsach.create')}}"><span class="title">Add category</span></a></li>
                            <li><a href="{{route('danhmucsach.index')}}"><span class="title">Show category</span></a></li>
                        </ul>

                    </li>
                    <li>
                        <a href="#" onclick="showbook()">
                            <span class="icon"><i class="fa fa-book" aria-hidden="true"></i>
                            </span>
                            <span class="title btn-book">Book</span>
                            <span class="icon"><i class="fa fa-caret-down" aria-hidden="true"></i>
                            </span>
                        </a>
                        <ul class="book-show">
                            <li><a href="{{route('sach.create')}}"><span class="title">Add Book</span></a></li>
                            <li><a href="{{route('sach.index')}}"><span class="title">Show Book</span></a></li>
                        </ul>
                    </li>

                    <li>
                        <a href="{{url('quanlymuonsach/require')}}">
                            <span class="icon"><i class="fa fa-check-square" aria-hidden="true"></i>
                            </span>
                            <span class="title">Require</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{url('quanlymuonsach')}}">
                            <span class="icon"><i class="fa fa-reply-all" aria-hidden="true"></i>
                            </span>
                            <span class="title">Borrow</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{route('thanhvien.index')}}">
                            <span class="icon"><i class="fa fa-id-card" aria-hidden="true"></i>
                            </span>
                            <span class="title">Member</span>
                        </a>
                    </li>
                    <li style="display:flex;">
                        <a href="#" style="width:60px;">
                            <span class="icon"><i class="fas fa-sign-out-alt" aria-hidden="true"></i>
                            </span>
                            <a href="{{route('logout')}}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();"><span class="title">Sign out</span></a>
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                            @csrf
                        </form>
                    </li>
                </ul>
            </div>
            <div class="toggle" onclick="toggleMenu()"><i class="fa fa-bars" aria-hidden="true"></i>
            </div>

            <script type="text/javascript">
                function toggleMenu() {
                    let navigation = document.querySelector('.navigation');
                    let toggle = document.querySelector('.toggle');
                    navigation.classList.toggle('ative');
                    toggle.classList.toggle('ative');
                }
                
                function showDDC() {
                    let ddc = document.querySelector('.DDC-show');
                    ddc.classList.toggle('show');

                }

                function showcategory() {
                    let category = document.querySelector('.category-show');
                    category.classList.toggle('show');

                }

                function showbook() {
                    let book = document.querySelector('.book-show');
                    book.classList.toggle('show');
                }
            </script>
        </div>


        <div class="content col-md-9">
            <div class="card-body">
                @if (session('status'))
                <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                </div>
                @endif

                @yield('content1')
            </div>
        </div>
    </div>
</div>
</div>
@endsection