routes/web.php
<?php
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SachController;
use App\Http\Controllers\DanhmucController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserpageController;
use App\Http\Controllers\QuanlyMuonsachController;
use App\Http\Controllers\ThanhvienController;
use App\Http\Controllers\MuonsachController;
use App\Models\DanhmucSach;
use App\Http\Controllers\DdcController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     $danhmuc = DanhmucSach::orderBy('id_Danhmuc','DESC')->get();
//     return view('homepage.userpage')->with(compact('danhmuc'));
// });

Route::get('/',[UserpageController::class, 'index']);
Route::get('ddc/{slugDDC}',[UserpageController::class, 'ddc']);
Route::get('/danh-muc/{slugdanhmuc}',[UserpageController::class, 'danhmuc']);
Route::get('/chi-tiet/{slugsach}',[UserpageController::class, 'chitiet'])->middleware('auth');
Route::get('/tim-kiem',[UserpageController::class, 'timkiem']);
Route::post('/muon-sach-1',[MuonsachController::class, 'store']);
Route::get('/muon-sach',[MuonsachController::class, 'index'])->middleware('auth');
Route::get('/the-thanh-vien',[UserpageController::class, 'thethanhvien'])->middleware('auth');







Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home')->middleware('checklogin');
Route::resource('/danhmucsach',DanhmucController::class);
Route::resource('/ddc',DdcController::class);
Route::resource('/sach',SachController::class);
Route::resource('/dashboard',DashboardController::class);
Route::get('/quanlymuonsach',[QuanlyMuonsachController::class, 'index'])->middleware('auth');
Route::get('/quanlymuonsach/require',[QuanlyMuonsachController::class, 'require'])->middleware('auth');
Route::post('/quanlymuonsach/dongy',[QuanlyMuonsachController::class, 'dongy']);
Route::post('/quanlymuonsach/tuchoi',[QuanlyMuonsachController::class, 'tuchoi']);
Route::post('/quanlymuonsach/datra',[QuanlyMuonsachController::class, 'datra']);
Route::resource('/thanhvien',ThanhvienController::class);





    
// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/DanhmucSach.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DanhmucSach extends Model
{
    use HasFactory;
    public $timestamps = false;
    protected $fillable = ['tendanhmuc','slugdanhmuc'];
    protected $primaryKey = 'id_Danhmuc';
    protected $table = 'danhmuc';

    public function sach()
    {
        return $this->hasMany('App\Models\Sach');
    }
}

resources/views/admin/danhmucsach/create.blade.php
@extends('home')

<!-- <head>
    <link href="{{ asset('css/dasboard.css') }}" rel="stylesheet">
</head> -->

@section('content1')
<!-- 
    <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card"> -->
            <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{url('/home')}}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Add category</li>
  </ol>
</nav>


<div class="card-header">{{ __('Thêm danh mục sách') }}</div>

@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif



    <form method="post" action="{{ route('danhmucsach.store')}}">

        @csrf

        <div class="form-group">
            <label for="tendanhmuc">Tên danh mục</label>
            <input type="text" class="form-control" value="{{ old('tendanhmuc')}}" onkeyup="ChangeToSlug()" name="tendanhmuc" id="slug" placeholder="Tên danh mục">
        </div>

        <div class="form-group">
            <label for="tendanhmuc">Slug danh mục</label>
            <input type="text" class="form-control" value="{{ old('slugdanhmuc')}}" name="slugdanhmuc" id="convert_slug" placeholder="Slug danh mục">
        </div>
        <!-- <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">Check me out</label>
                    </div> -->
        <button type="submit" class="btn btn-primary">Thêm</button>
    </form>
</div>

@endsection

resources/views/admin/danhmucsach/edit.blade.php
@extends('home')

<!-- <head>
    <link href="{{ asset('css/dasboard.css') }}" rel="stylesheet">
</head> -->

@section('content1')
<!-- 
    <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card"> -->

            <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{url('/home')}}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Edit category</li>
  </ol>
</nav>

<div class="card-header">{{ __('Cập nhật danh mục sách') }}</div>

@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif



    <form method="post" action="{{ route('danhmucsach.update',[$danhmucsach->id_Danhmuc])}}">
        @method('PUT')
        @csrf
        <div class="form-group">
            <label for="tendanhmuc">Tên danh mục</label>
            <input type="text" class="form-control" value="{{$danhmucsach->tendanhmuc}}" onkeyup="ChangeToSlug()" name="tendanhmuc" id="slug" placeholder="Tên danh mục">
        </div>
        <div class="form-group">
            <label for="slugdanhmuc">Slug danh mục</label>
            <input type="text" class="form-control" value="{{$danhmucsach->slugdanhmuc}}" name="slugdanhmuc" id="convert_slug" placeholder="Slug danh mục">
        </div>

        <!-- <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">Check me out</label>
                    </div> -->
        <button type="submit" class="btn btn-primary">Cập nhật</button>
    </form>
</div>

@endsection

resources/views/admin/danhmucsach/index.blade.php
@extends('home')

<!-- <head>
    <link href="{{ asset('css/dasboard.css') }}" rel="stylesheet">
</head> -->

@section('content1')

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{url('/home')}}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Show category</li>
  </ol>
</nav>

<div class="card-header">{{ __('Liệt kê danh mục sách') }}</div>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Stt</th>
                <th scope="col">Tên danh mục</th>
                <th scope="col">Slug danh mục</th>
                <th scope="col">Quản lý</th>
            </tr>
        </thead>
        <tbody>
            @foreach($danhmucsach as $key => $danhmuc)
            <tr>
                <th scope="row">{{$key}}</th>
                <td>{{$danhmuc->tendanhmuc}}</td>
                <td>{{$danhmuc->slugdanhmuc}}</td>
                <td>
                <div style="display:flex;">
                    <span><a href="{{route('danhmucsach.edit',[$danhmuc->id_Danhmuc])}}" class="btn btn-primary btn-sm">edit</a></span>
                    <form action="{{route('danhmucsach.destroy',[$danhmuc->id_Danhmuc])}}" method="post">
                        @method('DELETE')
                        @csrf
                        <span><button style="margin-left:5px;" onclick="return confirm('Bạn có muốn xóa danh mục này không')" class="btn btn-danger btn-sm">delete</button></span>
                    </form>
                </div>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

</div>
@endsection