routes/web.php
<?php
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SachController;
use App\Http\Controllers\DanhmucController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserpageController;
use App\Http\Controllers\QuanlyMuonsachController;
use App\Http\Controllers\ThanhvienController;
use App\Http\Controllers\MuonsachController;
use App\Models\DanhmucSach;
use App\Http\Controllers\DdcController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     $danhmuc = DanhmucSach::orderBy('id_Danhmuc','DESC')->get();
//     return view('homepage.userpage')->with(compact('danhmuc'));
// });

Route::get('/',[UserpageController::class, 'index']);
Route::get('ddc/{slugDDC}',[UserpageController::class, 'ddc']);
Route::get('/danh-muc/{slugdanhmuc}',[UserpageController::class, 'danhmuc']);
Route::get('/chi-tiet/{slugsach}',[UserpageController::class, 'chitiet'])->middleware('auth');
Route::get('/tim-kiem',[UserpageController::class, 'timkiem']);
Route::post('/muon-sach-1',[MuonsachController::class, 'store']);
Route::get('/muon-sach',[MuonsachController::class, 'index'])->middleware('auth');
Route::get('/the-thanh-vien',[UserpageController::class, 'thethanhvien'])->middleware('auth');







Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home')->middleware('checklogin');
Route::resource('/danhmucsach',DanhmucController::class);
Route::resource('/ddc',DdcController::class);
Route::resource('/sach',SachController::class);
Route::resource('/dashboard',DashboardController::class);
Route::get('/quanlymuonsach',[QuanlyMuonsachController::class, 'index'])->middleware('auth');
Route::get('/quanlymuonsach/require',[QuanlyMuonsachController::class, 'require'])->middleware('auth');
Route::post('/quanlymuonsach/dongy',[QuanlyMuonsachController::class, 'dongy']);
Route::post('/quanlymuonsach/tuchoi',[QuanlyMuonsachController::class, 'tuchoi']);
Route::post('/quanlymuonsach/datra',[QuanlyMuonsachController::class, 'datra']);
Route::resource('/thanhvien',ThanhvienController::class);





    
// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Ddc.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Ddc extends Model
{
    use HasFactory;
    public $timestamps = false;
    protected $fillable = ['malopDDC','tenlopDDC,slugDDC'];
    protected $primaryKey = 'malopDDC';
    protected $table = 'ddc';

    public function sach()
    {
        return $this->hasMany('App\Models\Sach');
    }
}

app/Http/Controllers/DdcController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Ddc;

class DdcController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ddc = Ddc::all();
        return view('admin.ddc.index') -> with(compact('ddc'));
    }
    

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.ddc.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'malopDDC' => 'required|unique:ddc|max:255',
            'tenlopDDC' => 'required|unique:ddc|max:255',
            'slugDDC' => 'required|unique:ddc|max:255',
        ],  
        [
            'malopDDC.unique' => 'mã lớp DDC đã có,vui lòng điền tên khác',
            'tenlopDDC.unique' => 'tên lớp DDC đã có,vui lòng điền tên khác',
            'malopDDC.required' => 'mã lớp DDC phải có nhé',
            'tenlopDDC.required' => 'tên lớp DDC phải có nhé',
        ]);

        $ddc = new Ddc();
        $ddc -> malopDDC = $validated['malopDDC'];
        $ddc -> tenlopDDC = $validated['tenlopDDC'];
        $ddc -> slugDDC = $validated['slugDDC'];
        $ddc ->save();
        return redirect()->back()->with('status','Thêm lớp DDC thành công');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($malopDDC)
    {
        $ddc = Ddc::find($malopDDC);
        return view('admin.ddc.edit') -> with(compact('ddc'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $malopDDC)
    {
        $validated = $request->validate([
            'malopDDC' => 'required|unique:ddc|max:255',
            'tenlopDDC' => 'required|unique:dcc|max:255',
            'slugDDC' => 'required|unique:ddc|max:255',
        ],  
        [
            'malopDDC.unique' => 'mã lớp DDC đã có,vui lòng điền tên khác',
            'tenlopDDC.unique' => 'tên lớp DDC đã có,vui lòng điền tên khác',
            'malopDDC.required' => 'mã lớp DDC phải có nhé',
            'tenlopDDC.required' => 'tên lớp DDC phải có nhé',
        ]);

        $ddc = Ddc::find($malopDDC);
        $ddc -> malopDDC = $validated['malopDDC'];
        $ddc -> tenlopDDC = $validated['tenlopDDC'];
        $ddc -> slugDDC = $validated['slugDDC'];
        $ddc ->save();
        return redirect()->back()->with('status','Cập nhật lớp DDC thành công');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($malopDDC)
    {
        Ddc::find($malopDDC)->delete();
        return redirect()->back()->with('status','Xóa lớp DDC thành công');
    }
}

resources/views/admin/ddc/create.blade.php
@extends('home')

<!-- <head>
    <link href="{{ asset('css/dasboard.css') }}" rel="stylesheet">
</head> -->

@section('content1')
<!-- 
    <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card"> -->
            <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{url('/home')}}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Add category</li>
  </ol>
</nav>


<div class="card-header">{{ __('Thêm lớp DDC') }}</div>

@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif



    <form method="post" action="{{ route('ddc.store')}}">

        @csrf
        <div class="form-group">
            <label for="malopDDC">Mã lớp DDC</label>
            <input type="text" class="form-control" value="{{ old('malopDDC')}}" name="malopDDC" placeholder="Mã lớp DDC">
        </div>

        <div class="form-group">
            <label for="tenlopDDC">Tên lớp DDC</label>
            <input type="text" class="form-control" value="{{ old('tenlopDDC')}}" onkeyup="ChangeToSlug()" name="tenlopDDC" id="slug" placeholder="Tên lớp DDC">
        </div>

        <div class="form-group">
            <label for="slugDDC">Slug DDC</label>
            <input type="text" class="form-control" value="{{ old('slugDDC')}}" name="slugDDC" id="convert_slug" placeholder="Slug DDC">
        </div>
        <!-- <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">Check me out</label>
                    </div> -->
        <button type="submit" class="btn btn-primary">Thêm</button>
    </form>
</div>

@endsection

resources/views/admin/ddc/edit.blade.php
@extends('home')

<!-- <head>
    <link href="{{ asset('css/dasboard.css') }}" rel="stylesheet">
</head> -->

@section('content1')
<!-- 
    <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card"> -->

            <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{url('/home')}}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Edit category</li>
  </ol>
</nav>

<div class="card-header">{{ __('Cập nhật danh mục sách') }}</div>

@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif



    <form method="post" action="{{ route('ddc.update',[$ddc->malopDDC])}}">
        @method('PUT')
        @csrf

        <div class="form-group">
            <label for="malopDDC">Mã lớp DDC</label>
            <input type="text" class="form-control" value="{{$ddc->malopDDC}}" name="malopDDC" placeholder="Mã lớp DDC">
        </div>
        
        <div class="form-group">
            <label for="tenlopDDC">Tên lớp DDC</label>
            <input type="text" class="form-control" value="{{$ddc->tenlopDDC}}" onkeyup="ChangeToSlug()" name="tenlopDDC" id="slug" placeholder="Tên lớp DDC">
        </div>
        <div class="form-group">
            <label for="slugdanhmuc">Slug DDC</label>
            <input type="text" class="form-control" value="{{$ddc->slugDDC}}" name="slugdanhmuc" id="convert_slug" placeholder="Slug DDC">
        </div>

        <!-- <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">Check me out</label>
                    </div> -->
        <button type="submit" class="btn btn-primary">Cập nhật</button>
    </form>
</div>

@endsection

resources/views/admin/ddc/index.blade.php
@extends('home')

<!-- <head>
    <link href="{{ asset('css/dasboard.css') }}" rel="stylesheet">
</head> -->

@section('content1')

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{url('/home')}}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Show category</li>
  </ol>
</nav>

<div class="card-header">{{ __('Liệt kê lớp DDC') }}</div>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Stt</th>
                <th scope="col">Mã lớp DDC</th>
                <th scope="col">Tên lớp DDC</th>
                <th scope="col">Slug DDC</th>
                <th scope="col">Quản lý</th>
            </tr>
        </thead>
        <tbody>
            @foreach($ddc as $key => $ddc)
            <tr>
                <th scope="row">{{$key}}</th>
                <td>{{$ddc->malopDDC}}</td>
                <?php
                dump($ddc->malopDDC);
                exit();
                ?>
                <td>{{$ddc->tenlopDDC}}</td>
                <td>{{$ddc->slugDDC}}</td>
                <td>
                <div style="display:flex;">
                    <span><a href="{{route('ddc.edit',[$ddc->malopDDC])}}" class="btn btn-primary btn-sm">edit</a></span>
                    <form action="{{route('ddc.destroy',[$ddc->malopDDC])}}" method="post">
                        @method('DELETE')
                        @csrf
                        <span><button style="margin-left:5px;" onclick="return confirm('Bạn có muốn xóa lớp DDC này không')" class="btn btn-danger btn-sm">delete</button></span>
                    </form>
                </div>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

</div>
@endsection