routes/web.php
<?php
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SachController;
use App\Http\Controllers\DanhmucController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserpageController;
use App\Http\Controllers\QuanlyMuonsachController;
use App\Http\Controllers\ThanhvienController;
use App\Http\Controllers\MuonsachController;
use App\Models\DanhmucSach;
use App\Http\Controllers\DdcController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     $danhmuc = DanhmucSach::orderBy('id_Danhmuc','DESC')->get();
//     return view('homepage.userpage')->with(compact('danhmuc'));
// });

Route::get('/',[UserpageController::class, 'index']);
Route::get('ddc/{slugDDC}',[UserpageController::class, 'ddc']);
Route::get('/danh-muc/{slugdanhmuc}',[UserpageController::class, 'danhmuc']);
Route::get('/chi-tiet/{slugsach}',[UserpageController::class, 'chitiet'])->middleware('auth');
Route::get('/tim-kiem',[UserpageController::class, 'timkiem']);
Route::post('/muon-sach-1',[MuonsachController::class, 'store']);
Route::get('/muon-sach',[MuonsachController::class, 'index'])->middleware('auth');
Route::get('/the-thanh-vien',[UserpageController::class, 'thethanhvien'])->middleware('auth');







Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home')->middleware('checklogin');
Route::resource('/danhmucsach',DanhmucController::class);
Route::resource('/ddc',DdcController::class);
Route::resource('/sach',SachController::class);
Route::resource('/dashboard',DashboardController::class);
Route::get('/quanlymuonsach',[QuanlyMuonsachController::class, 'index'])->middleware('auth');
Route::get('/quanlymuonsach/require',[QuanlyMuonsachController::class, 'require'])->middleware('auth');
Route::post('/quanlymuonsach/dongy',[QuanlyMuonsachController::class, 'dongy']);
Route::post('/quanlymuonsach/tuchoi',[QuanlyMuonsachController::class, 'tuchoi']);
Route::post('/quanlymuonsach/datra',[QuanlyMuonsachController::class, 'datra']);
Route::resource('/thanhvien',ThanhvienController::class);





    
// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Sach.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Sach extends Model
{
    use HasFactory;
    public $timestamps = false;
    protected $fillable = ['tensach','slugsach','tentacgia','id_Danhmuc','nhaxuatban','namxuatban','hinhanh','soluong','giabia','tomtat'];
    protected $primaryKey = 'id_Sach';
    protected $table = 'sach';
    
    public function danhmucsach()
    {
        return $this->belongsTo('App\Models\DanhmucSach', 'id_Danhmuc','id_Danhmuc');
    }

    public function ddc()
    {
        return $this->belongsTo('App\Models\Ddc', 'malopDDC','malopDDC');
    }

    public function muontra()
    {
        return $this->hasMany('App\Models\Muontra');
    }
}

app/Http/Controllers/SachController.php
<?php

namespace App\Http\Controllers;

use App\Models\DanhmucSach;
use App\Models\Sach;
use App\Models\Ddc;
use Illuminate\Http\Request;

class SachController extends Controller
{
    /**
     * 
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $list_sach = Sach::with('danhmucsach')->get();
        $list_sach = Sach::with('ddc')->get();
        $list_sach = Sach::all();
        return view('admin.sach.index')->with(compact('list_sach'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $danhmucsach = DanhmucSach::orderBy('id_Danhmuc','DESC')->get();
        $ddc = Ddc::orderBy('malopDDC','DESC')->get();
        return view('admin.sach.create')->with(compact('danhmucsach','ddc'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'tensach' => 'required|unique:sach|max:255',
            'slugsach' => 'required|unique:sach|max:255',
            'hinhanh' => 'required|image|mimes:jpg,png,gif,svg',
            'tomtat' => 'required|max:500',
            'nhaxuatban' => 'required',
            'soluong' => 'required',
            'giabia' => 'required',
            'namxuatban' => 'required',
            'tentacgia' => 'required',
            'danhmuc' => 'required',
            'ddc' => 'required'

        ],  
        [
            'tensach.required' => 'Tên sách phải có nhé',
            'slug.required' => 'Slug sách phải có nhé',
            'tensach.unique' => 'Tên sách đã có vui lòng chọn tên khác',
            'namxuatban.max' => 'Vui lòng nhập lại năm xuất bản',
            'hinhanh.required' => 'Hình ảnh phải có nhé',
            'tomtat.required' => 'Tóm tắt phải có nhé',

        ]);

        $sach = new Sach();
        $sach -> tensach = $validated['tensach'];
        $sach -> slugsach = $validated['slugsach'];
        $sach -> tomtat = $validated['tomtat'];
        $sach -> nhaxuatban = $validated['nhaxuatban'];
        $sach -> namxuatban = $validated['namxuatban'];
        $sach -> tentacgia = $validated['tentacgia'];
        $sach -> soluong = $validated['soluong'];
        $sach -> giabia = $validated['giabia'];
        $sach -> id_Danhmuc = $validated['danhmuc'];
        $sach -> malopDDC = $validated['ddc'];

        $get_image = $request->hinhanh;
        $path = 'uploads/sach';
        $get_name_image = $get_image->getClientOriginalName();
        $name_image = current(explode('.',$get_name_image));
        $new_image = $name_image.rand(0,99).'.'.$get_image->getClientOriginalExtension();
        $get_image->move($path,$new_image);

        $sach -> hinhanh = $new_image;

        $sach ->save();
        return redirect()->back()->with('status','Thêm sách thành công');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id_Sach)

    {   $sach = Sach::with('danhmucsach')->where('id_Sach',$id_Sach)  ->get();
        $danhmucsach = DanhmucSach::orderBy('id_Danhmuc','DESC')->get();
        $ddc = Ddc::orderBy('malopDDC','DESC')->get();
        $sach = Sach::find($id_Sach);
        return view('admin.sach.edit') -> with(compact('sach','danhmucsach','ddc'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id_Sach)
    {
        $validated = $request->validate([
            'tensach' => 'required|unique:sach|max:255',
            'slugsach' => 'required',
            'hinhanh' => 'required|image|mimes:jpg,png,gif,svg',
            'tomtat' => 'required|unique:sach|max:500',
            'nhaxuatban' => 'required',
            'namxuatban' => 'required',
            'soluong' => 'required',
            'giabia' => 'required',
            'tentacgia' => 'required',
            'danhmuc' => 'required',
            'ddc' => 'required'

        ],  
        [
            'tensach.required' => 'Tên sách phải có nhé',
            'tensach.unique' => 'Tên sách đã có vui lòng chọn tên khác',
            'hinhanh.required' => 'Hình ảnh phải có nhé',
            'namxuatban.max' => 'Vui lòng nhập lại năm xuất bản',
            'tomtat.required' => 'Tóm tắt phải có nhé',
            'namxuatban.required' => 'Vui lòng nhập đúng năm'

        ]);

        $sach = Sach::find($id_Sach);
        $sach -> tensach = $validated['tensach'];
        $sach -> slugsach = $validated['slugsach'];
        $sach -> tomtat = $validated['tomtat'];
        $sach -> nhaxuatban = $validated['nhaxuatban'];
        $sach -> namxuatban = $validated['namxuatban'];
        $sach -> tentacgia = $validated['tentacgia'];
        $sach -> soluong = $validated['soluong'];
        $sach -> giabia = $validated['giabia'];
        $sach -> id_Danhmuc = $validated['danhmuc'];
        $sach -> malopDDC = $validated['ddc'];

        $get_image = $request->hinhanh;
        $path = 'uploads/sach';
        $get_name_image = $get_image->getClientOriginalName();
        $name_image = current(explode('.',$get_name_image));
        $new_image = $name_image.rand(0,99).'.'.$get_image->getClientOriginalExtension();
        $get_image->move($path,$new_image);

        $sach -> hinhanh = $new_image;

        $sach ->save();
        return redirect()->back()->with('status','Cập nhật sách thành công');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id_Sach)
    {   $sach =  Sach::find($id_Sach);
        $path = 'uploads/sach'.$sach->hinhanh;
        if(file_exists($path))
        {
            unlink($path);
        }

        Sach::find($id_Sach)->delete();
        return redirect()->back()->with('status','Xóa sách thành công');
    }
}

resources/views/admin/sach/create.blade.php
@extends('home')

<!-- <head>
    <link href="{{ asset('css/dasboard.css') }}" rel="stylesheet">
</head> -->

@section('content1')
<!-- 
    <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card"> -->

            <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{url('/home')}}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Add book</li>
  </ol>
</nav>

<div class="card-header">{{ __('Thêm sách') }}</div>

 @if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif



<form method="post" action="{{ route('sach.store')}}" enctype="multipart/form-data">

    @csrf

    <div class="form-group">
        <label for="tensach">Tên sách</label>
        <input type="text" class="form-control" onkeyup="ChangeToSlug()" value="{{ old('tensach')}}" name="tensach" id="slug" placeholder="Tên sách">
    </div>
    <div class="form-group">
        <label for="slugsach">Slug sách</label>
        <input type="text" class="form-control" value="{{ old('slugsach')}}" name="slugsach" id="convert_slug" placeholder="Slug sách">
    </div>

    <div class="form-group">
        <label for="ddc">Tên lớp DDC</label>
        <select class="form-control" id="ddc" name="ddc">
            @foreach($ddc as $key => $muc)
            <option value="{{$muc->malopDDC}}">{{$muc->tenlopDDC}}</option>
            @endforeach
        </select>
    </div>

    <div class="form-group">
        <label for="danhmuc">Tên danh mục</label>
        <select class="form-control" id="danhmuc" name="danhmuc">
            @foreach($danhmucsach as $key => $muc)
            <option value="{{$muc->id_Danhmuc}}">{{$muc->tendanhmuc}}</option>
            @endforeach
        </select>
    </div>
  
    <div class="form-group">
        <label for="tacgia">Tác giả</label>
        <input type="text" class="form-control" value="{{ old('tentacgia')}}" name="tentacgia" id="tentacgia" placeholder="Tên tác giả">
    </div>
    <div class="form-group">
        <label for="namxuatban">Năm xuất bản</label>
        <input type="number" class="form-control" value="{{ old('namxuatban')}}" name="namxuatban" id="namxuatban" placeholder="Năm xuất bản" max=2021>
    </div>
    <div class="form-group">
        <label for="nhaxuatban">Nhà xuất bản</label>
        <input type="text" class="form-control" value="{{ old('nhaxuatban')}}" name="nhaxuatban" id="nhaxuatban" placeholder="Nhà xuất bản">
    </div>
    <div class="form-group">
        <label for="hinhanh">Hình ảnh</label>
        <input type="file" class="form-control-file" name="hinhanh">
    </div>

    <div class="form-group">
        <label for="soluong">Số lượng</label>
        <input type="number" class="form-control" name="soluong">
    </div>
    <div class="form-group">
        <label for="giabia">Giá bìa</label>
        <input type="number" class="form-control" name="giabia">
    </div>

    <div>
        <label for="tomtat">Tóm tắt</label>
        <textarea class="form-control"  name="tomtat" rows="5" style="resize: none;"></textarea>
    </div><br>
    <!-- <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">Check me out</label>
                    </div> -->
    <div>
        <button type="submit" class="btn btn-primary">Thêm</button>
    </div>
</form>

<script>
    document.getElementById("tentacgia").onblur = function() {
        this.value = ChuanhoaTen(this.value);
    };
    document.getElementById("nhaxuatban").onblur = function() {
        this.value = ChuanhoaTen(this.value);
    };
    function ChuanhoaTen(ten) {
        dname = ten;
        ss = dname.split(' ');
        dname = "";
        for (i = 0; i < ss.length; i++)
            if (ss[i].length > 0) {
                if (dname.length > 0) dname = dname + " ";
                dname = dname + ss[i].substring(0, 1).toUpperCase();
                dname = dname + ss[i].substring(1).toLowerCase();
            }
        return dname;
    }
</script>
</div>

@endsection

resources/views/admin/sach/edit.blade.php
@extends('home')

<!-- <head>
    <link href="{{ asset('css/dasboard.css') }}" rel="stylesheet">
</head> -->

@section('content1')
<!-- 
    <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card"> -->

            <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{url('/home')}}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Edit book/li>
  </ol>
</nav>

<div class="card-header">{{ __('Cập nhật sách') }}</div>

@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif



<form method="post" action="{{ route('sach.update',[$sach->id_Sach])}}" enctype="multipart/form-data">
    @method('PUT')
    @csrf

    <div class="form-group">
        <label for="tensach">Tên sách</label>
        <input type="text" class="form-control" onkeyup="ChangeToSlug()" value="{{$sach->tensach}}" name="tensach" id="slug" placeholder="Tên sách">
    </div>
    <div class="form-group">
        <label for="slugsach">Slug sách</label>
        <input type="text" class="form-control" value="{{$sach->slugsach}}" name="slugsach" id="convert_slug" placeholder="Slug sách">
    </div>

    <div class="form-group">
        <label for="ddc">Tên lớp DDC</label>
        <select class="form-control" id="ddc" name="ddc">
            @foreach($ddc as $key => $muc)
            <option {{$muc->malopDDC == $sach->malopDDC ? 'selected' : ''}} value="{{$muc->malopDDC}}">{{$muc->tenlopDDC}}</option>
            @endforeach
        </select>
    </div>

    <div class="form-group">
        <label for="danhmuc">Tên danh mục</label>
        <select class="form-control" id="danhmuc" name="danhmuc">
            @foreach($danhmucsach as $key => $muc)
            <option {{$muc->id_Danhmuc == $sach->id_Danhmuc ? 'selected' : ''}} value="{{$muc->id_Danhmuc}}">{{$muc->tendanhmuc}}</option>
            @endforeach
        </select>
    </div>
    <div class="form-group">
        <label for="tacgia">Tác giả</label>
        <input type="text" class="form-control" value="{{$sach->tentacgia}}" name="tentacgia" id="tentacgia" placeholder="Tên tác giả">
    </div>
    <div class="form-group">
        <label for="namxuatban">Năm xuất bản</label>
        <input type="number" class="form-control" value="{{$sach->namxuatban}}" name="namxuatban" id="namxuatban" placeholder="Năm xuất bản" max=2021>
    </div>
    <div class="form-group">
        <label for="nhaxuatban">Nhà xuất bản</label>
        <input type="text" class="form-control" value="{{$sach->nhaxuatban}}" name="nhaxuatban" id="nhaxuatban" placeholder="Nhà xuất bản">
    </div>
    <div class="form-group">
        <label for="hinhanh">Hình ảnh</label>
        <input type="file" class="form-control-file" name="hinhanh">
        <img src="{{asset('uploads/sach/'.$sach->hinhanh)}}" height="180px" width="100px">
    </div>
    <div class="form-group">
        <label for="soluong">Số lượng</label>
        <input type="text" class="form-control" value="{{$sach->soluong}}" name="soluong" id="soluong" placeholder="Số lượng">
    </div>
    <div class="form-group">
        <label for="giabia">Giá bìa</label>
        <input type="text" class="form-control" value="{{$sach->giabia}}" name="giabia" id="giabia" placeholder="Giá bìa">
    </div>
    <div>
        <label for="tomtat">Tóm tắt</label>
        <textarea class="form-control" value="{{$sach->tomtat}}" name="tomtat" rows="5" style="resize: none;"></textarea>
    </div><br>
    <!-- <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">Check me out</label>
                    </div> -->
    <div>
        <button type="submit" class="btn btn-primary">Câp nhật</button>
    </div>
</form>

<script>
    document.getElementById("tentacgia").onblur = function() {
        this.value = ChuanhoaTen(this.value);
    };

    document.getElementById("nhaxuatban").onblur = function() {
        this.value = ChuanhoaTen(this.value);
    };

    function ChuanhoaTen(ten) {
        dname = ten;
        ss = dname.split(' ');
        dname = "";
        for (i = 0; i < ss.length; i++)
            if (ss[i].length > 0) {
                if (dname.length > 0) dname = dname + " ";
                dname = dname + ss[i].substring(0, 1).toUpperCase();
                dname = dname + ss[i].substring(1).toLowerCase();
            }
        return dname;
    }
</script>
</div>

@endsection

resources/views/admin/sach/index.blade.php
@extends('home')

<!-- <head>
    <link href="{{ asset('css/dasboard.css') }}" rel="stylesheet">
</head> -->

@section('content1')

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{url('/home')}}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Show book</li>
  </ol>
</nav>

<div class="card-header">{{ __('Liệt kê sách') }}</div>

<table class="table sortable">
    <thead>
        <tr>
            <th scope="col">STT</th>
            <th scope="col" class="sortcol">Tên sách</th>
            <th scope="col">Slug sách</th>
            <th scope="col">Tên tác giả</th>
			<th scope="col"> Lớp DDC </th>
            <th scope="col"> Danh mục </th>
            <th scope="col"> Nhà xuất bản </th>
            <th scope="col"> Năm xuất bản</th>
            <th scope="col"> Hình ảnh </th>
            <th scope="col">Số lượng</th>
            <th scope="col">Giá bìa</th>
            <th scope="col"> Quản lý </th>

        </tr>
    </thead>
    <tbody class="tbody">
        @foreach($list_sach as $key => $sach)
        <tr>
            <td scope="row">{{$key}}</td>
            <td>{{$sach->tensach}}</td>
            <td>{{$sach->slugsach}}</td>
            <td>{{$sach->tentacgia}}</td>
			<td>{{$sach->ddc->tenlopDDC}}</td>
            <td>{{$sach->danhmucsach->tendanhmuc}}</td>
            <td>{{$sach->nhaxuatban}}</td>
            <td>{{$sach->namxuatban}}</td>
            <td><img src="{{asset('uploads/sach/'.$sach->hinhanh)}}" height="180px" width="150px" </td>
            <td>{{$sach->soluong}}</td>
            <td>{{$sach->giabia}}</td>
            <td>
                <div style="display:flex;">
                <a href="{{route('sach.edit',[$sach->id_Sach])}}" class="btn btn-primary btn-sm">edit</a>
                <form action="{{route('sach.destroy',[$sach->id_Sach])}}" method="post">
                    @method('DELETE')
                    @csrf
                    <button style="margin-left: 5px;;" onclick="return confirm('Bạn có muốn xóa danh mục này không')" class="btn btn-danger btn-sm">delete</button>

                </form>
            </div>
            </td>
            
        </tr>
        @endforeach
    </tbody>
</table>

</div>
<script>
    // Lấy tham chiếu đến tất cả các bảng sắp xếp được
var tbls = document.querySelectorAll("table.sortable");
// Tiền xử lý các bảng, cột sắp xếp được
for (var i = 0; i < tbls.length; i++)
	preProcessSortableTbl(tbls[i]);
// Hàm tiền xử lý
function preProcessSortableTbl(tbl) {
	// Do chưa biết trước số bảng sắp xếp được
	// nên không thể dùng các biến toàn cục để
	// biểu thị cột và chiều đang được sắp xếp cho từng bảng
	// như ở ví dụ đơn giản.

	// Giải pháp: Thêm vào trước mỗi bảng sắp xếp được 
	// 2 đối tượng hidden để lưu thông tin
	// cột và chiều đang được sắp xếp trên bảng.

	var col = document.createElement("input");
	var dir = document.createElement("input");
	col.type = "hidden";
	dir.type = "hidden";
	col.value = "-1";
	dir.value = "";
	tbl.parentNode.insertBefore(col, tbl);
	tbl.parentNode.insertBefore(dir, tbl);

	// Tiền xử lý các ô tiêu đề cột sắp xếp được
	var hcells = tbl.rows[0].cells;
	for (var i = 0; i < hcells.length; i++)
		if (hcells[i].classList.contains("sortcol")) { // là cột sắp xếp được
			// Chèn đối tượng <span class="arrow"></span> vào cuối tiêu đề
			// để biểu thị mũi tên chiều sắp xếp.
			hcells[i].innerHTML += '<span class="arrow"></span>';
 
			// Xử lý sự kiện kích chuột trên ô tiêu đề
			hcells[i].onclick = function() {
				// Cột và chiều đang được sắp xếp trên bảng chứa ô tiêu đề
				var d = this.parentNode.parentNode.parentNode.previousSibling;
				var c = d.previousSibling;

				// Bỏ biểu thị cột đang được sắp xếp (nếu có)
				var j;
				for (j = 0; j < this.parentNode.cells.length; j++) {
					this.parentNode.cells[j].classList.remove("asc");
					this.parentNode.cells[j].classList.remove("desc");
				}

				// Lấy chỉ mục của ô tiêu đề
				// (có thể gộp với vòng for trên cho tối ưu nhưng
				//  được tác ra cho dễ hiểu)
				for (j = 0; j < this.parentNode.cells.length; j++)
					if (this.parentNode.cells[j] == this) break;

				if (c.value == j.toString()) {
					// Cột chứa ô tiêu đề đang được sắp xếp, đảo chiều
					d.value = (d.value == "desc" ? "asc" : "desc");

				} else {
					// Mặc định sắp xếp tăng dần
					c.value = j.toString();
					d.value = "asc";
				}

				// Thêm biểu thị cột được sắp xếp
				this.classList.add(d.value);

				// Sắp xếp
				sortTbl(this.parentNode.parentNode.parentNode);
			};
	}
}


// Sắp xếp dữ liệu trong bảng, trừ cột 1
// Có thể mở rộng hàm này để cho biết có đảo cả cột 1 hay không
function sortTbl(tbl) {
	var dir = tbl.previousSibling.value;
	var col = parseInt(tbl.previousSibling.previousSibling.value);

	for (var i = 1; i < tbl.rows.length; i++)
		for (var j = i+1; j < tbl.rows.length; j++) 
			if ((dir == "asc" && tbl.rows[i].cells[col].innerHTML.toLowerCase() > 
				tbl.rows[j].cells[col].innerHTML.toLowerCase()) || 
				(dir == "desc" && tbl.rows[i].cells[col].innerHTML.toLowerCase() <
				tbl.rows[j].cells[col].innerHTML.toLowerCase())) {
					//hoán vị
					for (var t = 1; t < tbl.rows[i].cells.length; t++) {
						tmp = tbl.rows[i].cells[t].innerHTML;
						tbl.rows[i].cells[t].innerHTML = tbl.rows[j].cells[t].innerHTML;
						tbl.rows[j].cells[t].innerHTML = tmp;
					}				
			}
}


</script>
@endsection